# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IcarusGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 332)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.batteryProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.batteryProgressBar.setGeometry(QtCore.QRect(80, 60, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.batteryProgressBar.setFont(font)
        self.batteryProgressBar.setAcceptDrops(False)
        self.batteryProgressBar.setAutoFillBackground(False)
        self.batteryProgressBar.setStyleSheet("")
        self.batteryProgressBar.setMaximum(100)
        self.batteryProgressBar.setProperty("value", 24)
        self.batteryProgressBar.setTextVisible(False)
        self.batteryProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.batteryProgressBar.setInvertedAppearance(False)
        self.batteryProgressBar.setObjectName("batteryProgressBar")
        self.ChamberPProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ChamberPProgressBar.setGeometry(QtCore.QRect(80, 120, 221, 21))
        self.ChamberPProgressBar.setProperty("value", 24)
        self.ChamberPProgressBar.setTextVisible(False)
        self.ChamberPProgressBar.setObjectName("ChamberPProgressBar")
        self.ChamberTProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ChamberTProgressBar.setGeometry(QtCore.QRect(80, 180, 221, 21))
        self.ChamberTProgressBar.setProperty("value", 24)
        self.ChamberTProgressBar.setTextVisible(False)
        self.ChamberTProgressBar.setObjectName("ChamberTProgressBar")
        self.ThrustProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ThrustProgressBar.setGeometry(QtCore.QRect(80, 240, 221, 21))
        self.ThrustProgressBar.setProperty("value", 24)
        self.ThrustProgressBar.setTextVisible(False)
        self.ThrustProgressBar.setObjectName("ThrustProgressBar")
        self.launchPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.launchPushButton.setGeometry(QtCore.QRect(390, 100, 111, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.launchPushButton.setFont(font)
        self.launchPushButton.setObjectName("launchPushButton")
        self.ignitorSafetyCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ignitorSafetyCheckBox.setGeometry(QtCore.QRect(390, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ignitorSafetyCheckBox.setFont(font)
        self.ignitorSafetyCheckBox.setChecked(True)
        self.ignitorSafetyCheckBox.setObjectName("ignitorSafetyCheckBox")
        self.logdataRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.logdataRadio.setGeometry(QtCore.QRect(390, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.logdataRadio.setFont(font)
        self.logdataRadio.setChecked(False)
        self.logdataRadio.setObjectName("logdataRadio")
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileNameLineEdit.setGeometry(QtCore.QRect(390, 40, 111, 20))
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.BatteryLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.BatteryLCD.setGeometry(QtCore.QRect(10, 60, 64, 23))
        self.BatteryLCD.setSmallDecimalPoint(True)
        self.BatteryLCD.setObjectName("BatteryLCD")
        self.ChamberPLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.ChamberPLCD.setGeometry(QtCore.QRect(10, 120, 64, 23))
        self.ChamberPLCD.setSmallDecimalPoint(True)
        self.ChamberPLCD.setObjectName("ChamberPLCD")
        self.chamberTLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.chamberTLCD.setGeometry(QtCore.QRect(10, 180, 64, 23))
        self.chamberTLCD.setSmallDecimalPoint(True)
        self.chamberTLCD.setObjectName("chamberTLCD")
        self.ThrustLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.ThrustLCD.setGeometry(QtCore.QRect(10, 240, 64, 23))
        self.ThrustLCD.setSmallDecimalPoint(True)
        self.ThrustLCD.setObjectName("ThrustLCD")
        self.batteryLabel = QtWidgets.QLabel(self.centralwidget)
        self.batteryLabel.setGeometry(QtCore.QRect(80, 32, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.batteryLabel.setFont(font)
        self.batteryLabel.setObjectName("batteryLabel")
        self.chamberPLabel = QtWidgets.QLabel(self.centralwidget)
        self.chamberPLabel.setGeometry(QtCore.QRect(80, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chamberPLabel.setFont(font)
        self.chamberPLabel.setObjectName("chamberPLabel")
        self.chamberTLabel = QtWidgets.QLabel(self.centralwidget)
        self.chamberTLabel.setGeometry(QtCore.QRect(80, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chamberTLabel.setFont(font)
        self.chamberTLabel.setObjectName("chamberTLabel")
        self.thrustLabel = QtWidgets.QLabel(self.centralwidget)
        self.thrustLabel.setGeometry(QtCore.QRect(80, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.thrustLabel.setFont(font)
        self.thrustLabel.setObjectName("thrustLabel")
        self.rpLabel = QtWidgets.QLabel(self.centralwidget)
        self.rpLabel.setGeometry(QtCore.QRect(340, 210, 181, 91))
        self.rpLabel.setText("")
        self.rpLabel.setPixmap(QtGui.QPixmap("LOGO-RocketProject-highres-trnsprnt-bckgd.png"))
        self.rpLabel.setScaledContents(True)
        self.rpLabel.setObjectName("rpLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.launchPushButton.setText(_translate("MainWindow", "Launch"))
        self.ignitorSafetyCheckBox.setText(_translate("MainWindow", "Ignitor Safety"))
        self.logdataRadio.setText(_translate("MainWindow", "Log Data"))
        self.fileNameLineEdit.setText(_translate("MainWindow", "data.txt"))
        self.batteryLabel.setText(_translate("MainWindow", "Battery Voltage"))
        self.chamberPLabel.setText(_translate("MainWindow", "Chamber Pressure"))
        self.chamberTLabel.setText(_translate("MainWindow", "Chamber Temperature"))
        self.thrustLabel.setText(_translate("MainWindow", "Thrust"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

